force-app/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

quiz-app/force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Text__c.field-meta.xml
<CustomField>
    <fullName>Question_Text__c</fullName>
    <label>Question Text</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

quiz-app/force-app/main/default/objects/Question_Choice__c/Question_Choice__c.object-meta.xml
<CustomObject>
    <label>Question Choice</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Question Choice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Choices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

quiz-app/force-app/main/default/objects/Question_Choice__c/fields/Choice_Text__c.field-meta.xml
<CustomField>
    <fullName>Choice_Text__c</fullName>
    <label>Choice Text</label>
    <length>700</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question_Choice__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Question Choices</relationshipLabel>
    <relationshipName>Question_Choices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

quiz-app/force-app/main/default/classes/ExamQAViewerController.cls
public without sharing class ExamQAViewerController {
    @AuraEnabled(cacheable=true)
    public static List<Question__c> getQuestionAnswers() {
        //System.debug(ApexPages.currentPage().getParameters());
        List<Question__c> questionAnswersList = [SELECT Id, Question_Text__c, 
                                                 		(SELECT Id, Choice_Text__c, Is_Correct__c 
                                                         FROM Question_Choices__r ORDER BY CreatedDate) 
                                                 FROM Question__c WHERE Exam__c = 'a01dM000023uneQQAQ' ORDER BY CreatedDate ];
        return questionAnswersList; 
    }
}